[[ -f $XDG_CONFIG_HOME/X11/Xresources ]] \
	&& xrdb -merge -I$HOME $XDG_CONFIG_HOME/X11/Xresources

udiskie &

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

systemctl start --user graphical-session.target

exec i3

